import type {Metadata} from "next";
import "./globals.css";
import '@ant-design/v5-patch-for-react-19';
import Header from "@/widgets/header/ui/header";
import Footer from "@/widgets/footer/ui/footer";
import RootProvider from "@/shared/providers/RootProvider";
import { Roboto } from 'next/font/google'


const roboto = Roboto({
    weight: ["100", "300", "400", "500", "700", "900"],
    subsets: ['latin', 'cyrillic'],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={roboto.className}>
        <RootProvider>
            <Header/>
            <main>{children}</main>
            <Footer/>
        </RootProvider>
        </body>
        </html>
    );
}
